package release

import data.lib

test_exception {
	# lib.assert_equal(exception, {["bad_day"]})
	lib.assert_equal(exception, {[]})
}
